name: Send Message Card to Webhook

on:
  push:

jobs:
  send-message-card:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get current date and time
        id: current_time
        run: echo "CURRENT_TIME=$(date -u '+%M:%S, %d/%m/%Y')" >> $GITHUB_ENV

      - name: Send Message Card to Webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          REPO_NAME: ${{ github.repository }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          CURRENT_TIME: ${{ env.CURRENT_TIME }}
        run: |
          FULL_NAME="${REPO_NAME}/${BRANCH_NAME}"
          COMMIT_TITLE=$(git log -1 --pretty=format:%s)
          COMMIT_DESCRIPTION=$(git log -1 --pretty=format:%b)

          MESSAGE_CARD_JSON=$(cat <<EOF
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "summary": "GitHub | Attention Required",
            "themeColor": "0076D7",
            "sections": [
              {
                "activityTitle": "GitHub | Attention Required",
                "activitySubtitle": "Sent $CURRENT_TIME",
                "activityImage": "https://statics.teams.cdn.office.net/evergreen-assets/apps/c3a1996d-db0f-4857-a6ea-7aabf0266b00_largeImage.png?v=1.1.1",
                "facts": [
                  {
                    "name": "Repository:",
                    "value": "$FULL_NAME"
                  },
                  {
                    "name": "Committer:",
                    "value": "${{ github.actor }}"
                  },
                  {
                    "name": "Title:",
                    "value": "$COMMIT_TITLE"
                  },
                  {
                    "name": "Description:",
                    "value": "$COMMIT_DESCRIPTION"
                  }
                ],
                "text": "A new commit was made to **$FULL_NAME**."
              }
            ],
            "potentialAction": [
              {
                "@type": "OpenUri",
                "name": "View commit",
                "targets": [
                  {
                    "os": "default",
                    "uri": "${{ github.event.head_commit.url }}"
                  }
                ]
              }
            ],
            "text": "Please note: this is an automated message."
          }
          EOF
          )

          curl -X POST -H "Content-Type: application/json" -d "$MESSAGE_CARD_JSON" $WEBHOOK_URL
